apiVersion: v1
kind: ConfigMap
metadata:
  name: dog-breeds-api-config
  namespace: dog-breeds
  labels:
    app: dog-breeds
    component: api
data:
  DOG_BREEDS_DB_HOST: "dog-breeds-db.dog-breeds.svc.cluster.local"
  DOG_BREEDS_DB_PORT: "5432"
  DOG_BREEDS_DB_NAME: "dog_breeds_db"
  DOG_BREEDS_DB_USER: "airflow"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  ALLOWED_ORIGINS: "*"

