apiVersion: v1
kind: ConfigMap
metadata:
  name: dog-breeds-db-config
  namespace: dog-breeds
  labels:
    app: dog-breeds
    component: database
data:
  POSTGRES_DB: "dog_breeds_db"
  POSTGRES_USER: "airflow"
  # Schema is mounted as init script via another ConfigMap

